### ISSUE TITLE
unable to install with ansible-galaxy

### ISSUE THREAD

**Issue by lemmy04** [ahuffman/ansible-yp#2]
[root@rhel8vm ~]# ansible-galaxy install ahuffman.yp
- downloading role 'yp', owned by ahuffman
 [WARNING]: - ahuffman.yp was NOT installed successfully: Unable to compare role versions (1.0.4, v1.0.1, v1.0.3, v1.0, v1.0.2) to determine the most
recent version due to incompatible version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role
version to install.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by ahuffman** [comment]
Removed old releases that contained a `v` in front of the release/version numbers.

@lemmy04 Just tested the install after old version clean up.  Working now.
